### ISSUE TITLE
Should a .help() be included in each of the Libraries?

### ISSUE THREAD

**Issue by Narrev** [Quenty/NevermoreEngine#27]
I put an os.help() in my os module, should the same functionality be applied to all modules? There should at least be some way to access documentation on how to use modules such as the Ripple effect. I'd like to use libraries without trying to decipher and figure out which functions are used internally and which I should use to achieve my endgoal

**Comment by Quenty** [comment]
Narrev, let me get back to you on these pull requests in a bit, sorry for the delay.

As for this, I prefer in-lined documentation for each method. Calling .help() implies the libraries are loaded during studio, (which by default they are not). Instead, the standard LuaDoc documentation method is being used (with the exception that the documentation is inside of the function, for easier folding).

https://github.com/Quenty/NevermoreEngine/blob/master/Modules/qGUI/PaperRipple/Ripple.lua#L7

For example, this code here is pretty well documented. 

The real issue here is that 
I noticed you said that you didn't know which API components were public/private. I think that that documentation _should_ be included, and I'll be working to note which parts are.
