### ISSUE TITLE
Is this still actively updated and supported still?

### ISSUE THREAD

**Issue by ToastEngine** [Quenty/NevermoreEngine#55]

**Comment by Narrev** [comment]
Kinda

**Comment by devSparkle** [comment]
Sometimes.

**Comment by Narrev** [comment]
Nevermore is currently undergoing a major change in the way it works. Not that anyone is currently working on that xP

We might have to create a sequel because it is just too hard to reach Quenty. Maybe devSparkle and I should do a voice call sometime to discuss the future of the Nevermore plugin, and work on it together if possible.

**Comment by devSparkle** [comment]
Agreed. My exams are taking up all my time, but they will be over in a month, when I can start writing code.

It would be interesting to create a GitHub organization containing repositories for the engine and its submodules. We could then have an extension that would poll the repositories, and allow the user to select which modules to install in their game.
